package com.clawgui.ng.runtime.phone.config

object Apps {

    val APP_PACKAGES: Map<String, String> = mapOf(
        // Social & Messaging
        "微信" to "com.tencent.mm",
        "QQ" to "com.tencent.mobileqq",
        "qq" to "com.tencent.mobileqq",
        "微博" to "com.sina.weibo",
        "Weibo" to "com.sina.weibo",
        "weibo" to "com.sina.weibo",
        // Payment
        "支付宝" to "com.eg.android.AlipayGphone",
        "Alipay" to "com.eg.android.AlipayGphone",
        "alipay" to "com.eg.android.AlipayGphone",
        // E-commerce
        "淘宝" to "com.taobao.taobao",
        "Taobao" to "com.taobao.taobao",
        "taobao" to "com.taobao.taobao",
        "京东" to "com.jingdong.app.mall",
        "JD" to "com.jingdong.app.mall",
        "jd" to "com.jingdong.app.mall",
        "拼多多" to "com.xunmeng.pinduoduo",
        "PDD" to "com.xunmeng.pinduoduo",
        "pdd" to "com.xunmeng.pinduoduo",
        "淘宝闪购" to "com.taobao.taobao",
        "京东秒送" to "com.jingdong.app.mall",
        // Lifestyle & Social
        "小红书" to "com.xingin.xhs",
        "小红薯" to "com.xingin.xhs",
        "Xiaohongshu" to "com.xingin.xhs",
        "xiaohongshu" to "com.xingin.xhs",
        "xhs" to "com.xingin.xhs",
        "豆瓣" to "com.douban.frodo",
        "Douban" to "com.douban.frodo",
        "douban" to "com.douban.frodo",
        "知乎" to "com.zhihu.android",
        "Zhihu" to "com.zhihu.android",
        "zhihu" to "com.zhihu.android",
        // Maps & Navigation
        "高德地图" to "com.autonavi.minimap",
        "高德" to "com.autonavi.minimap",
        "高德导航" to "com.autonavi.minimap",
        "Amap" to "com.autonavi.minimap",
        "amap" to "com.autonavi.minimap",
        "百度地图" to "com.baidu.BaiduMap",
        // Food & Services
        "美团" to "com.sankuai.meituan",
        "Meituan" to "com.sankuai.meituan",
        "meituan" to "com.sankuai.meituan",
        "大众点评" to "com.dianping.v1",
        "点评" to "com.dianping.v1",
        "饿了么" to "me.ele",
        "Eleme" to "me.ele",
        "eleme" to "me.ele",
        "肯德基" to "com.yek.android.kfc.activitys",
        "KFC" to "com.yek.android.kfc.activitys",
        // Travel
        "携程" to "ctrip.android.view",
        "Ctrip" to "ctrip.android.view",
        "ctrip" to "ctrip.android.view",
        "铁路12306" to "com.MobileTicket",
        "12306" to "com.MobileTicket",
        "去哪儿" to "com.Qunar",
        "去哪儿旅行" to "com.Qunar",
        "滴滴出行" to "com.sdu.didi.psnger",
        "滴滴" to "com.sdu.didi.psnger",
        "Didi" to "com.sdu.didi.psnger",
        "didi" to "com.sdu.didi.psnger",
        // Video & Entertainment
        "bilibili" to "tv.danmaku.bili",
        "Bilibili" to "tv.danmaku.bili",
        "BiliBili" to "tv.danmaku.bili",
        "哔哩哔哩" to "tv.danmaku.bili",
        "B站" to "tv.danmaku.bili",
        "b站" to "tv.danmaku.bili",
        "小破站" to "tv.danmaku.bili",
        "抖音" to "com.ss.android.ugc.aweme",
        "Douyin" to "com.ss.android.ugc.aweme",
        "douyin" to "com.ss.android.ugc.aweme",
        "快手" to "com.smile.gifmaker",
        "Kuaishou" to "com.smile.gifmaker",
        "kuaishou" to "com.smile.gifmaker",
        "腾讯视频" to "com.tencent.qqlive",
        "Tencent Video" to "com.tencent.qqlive",
        "爱奇艺" to "com.qiyi.video",
        "iQiyi" to "com.qiyi.video",
        "iqiyi" to "com.qiyi.video",
        "优酷视频" to "com.youku.phone",
        "优酷" to "com.youku.phone",
        "Youku" to "com.youku.phone",
        "youku" to "com.youku.phone",
        "芒果TV" to "com.hunantv.imgo.activity",
        "芒果tv" to "com.hunantv.imgo.activity",
        "芒果" to "com.hunantv.imgo.activity",
        "红果短剧" to "com.phoenix.read",
        "红果" to "com.phoenix.read",
        // Music & Audio
        "网易云音乐" to "com.netease.cloudmusic",
        "网易云" to "com.netease.cloudmusic",
        "网易音乐" to "com.netease.cloudmusic",
        "NetEase Music" to "com.netease.cloudmusic",
        "QQ音乐" to "com.tencent.qqmusic",
        "qq音乐" to "com.tencent.qqmusic",
        "QQMusic" to "com.tencent.qqmusic",
        "qqmusic" to "com.tencent.qqmusic",
        "汽水音乐" to "com.luna.music",
        "喜马拉雅" to "com.ximalaya.ting.android",
        "Ximalaya" to "com.ximalaya.ting.android",
        "ximalaya" to "com.ximalaya.ting.android",
        // Reading
        "番茄小说" to "com.dragon.read",
        "番茄免费小说" to "com.dragon.read",
        "番茄" to "com.dragon.read",
        "七猫免费小说" to "com.kmxs.reader",
        "七猫" to "com.kmxs.reader",
        "七猫小说" to "com.kmxs.reader",
        // Productivity
        "飞书" to "com.ss.android.lark",
        "Feishu" to "com.ss.android.lark",
        "feishu" to "com.ss.android.lark",
        "Lark" to "com.ss.android.lark",
        "lark" to "com.ss.android.lark",
        "QQ邮箱" to "com.tencent.androidqqmail",
        // AI & Tools
        "豆包" to "com.larus.nova",
        "Doubao" to "com.larus.nova",
        "doubao" to "com.larus.nova",
        // Health & Fitness
        "keep" to "com.gotokeep.keep",
        "美柚" to "com.lingan.seeyou",
        // News & Information
        "腾讯新闻" to "com.tencent.news",
        "今日头条" to "com.ss.android.article.news",
        // Real Estate
        "贝壳找房" to "com.lianjia.beike",
        "安居客" to "com.anjuke.android.app",
        // Finance
        "同花顺" to "com.hexin.plat.android",
        // Games
        "星穹铁道" to "com.miHoYo.hkrpg",
        "崩坏：星穹铁道" to "com.miHoYo.hkrpg",
        "恋与深空" to "com.papegames.lysk.cn",
        // System & Utilities
        "AndroidSystemSettings" to "com.android.settings",
        "Android System Settings" to "com.android.settings",
        "Android  System Settings" to "com.android.settings",
        "Android-System-Settings" to "com.android.settings",
        "Settings" to "com.android.settings",
        "AudioRecorder" to "com.android.soundrecorder",
        "audiorecorder" to "com.android.soundrecorder",
        // International apps
        "Bluecoins" to "com.rammigsoftware.bluecoins",
        "bluecoins" to "com.rammigsoftware.bluecoins",
        "Broccoli" to "com.flauschcode.broccoli",
        "broccoli" to "com.flauschcode.broccoli",
        "Booking.com" to "com.booking",
        "Booking" to "com.booking",
        "booking.com" to "com.booking",
        "booking" to "com.booking",
        "BOOKING.COM" to "com.booking",
        "Chrome" to "com.android.chrome",
        "chrome" to "com.android.chrome",
        "Google Chrome" to "com.android.chrome",
        "Clock" to "com.android.deskclock",
        "clock" to "com.android.deskclock",
        "Contacts" to "com.android.contacts",
        "contacts" to "com.android.contacts",
        "Duolingo" to "com.duolingo",
        "duolingo" to "com.duolingo",
        "Expedia" to "com.expedia.bookings",
        "expedia" to "com.expedia.bookings",
        "Files" to "com.android.fileexplorer",
        "files" to "com.android.fileexplorer",
        "File Manager" to "com.android.fileexplorer",
        "file manager" to "com.android.fileexplorer",
        "gmail" to "com.google.android.gm",
        "Gmail" to "com.google.android.gm",
        "GoogleMail" to "com.google.android.gm",
        "Google Mail" to "com.google.android.gm",
        "GoogleFiles" to "com.google.android.apps.nbu.files",
        "googlefiles" to "com.google.android.apps.nbu.files",
        "FilesbyGoogle" to "com.google.android.apps.nbu.files",
        "GoogleCalendar" to "com.google.android.calendar",
        "Google-Calendar" to "com.google.android.calendar",
        "Google Calendar" to "com.google.android.calendar",
        "google-calendar" to "com.google.android.calendar",
        "google calendar" to "com.google.android.calendar",
        "GoogleChat" to "com.google.android.apps.dynamite",
        "Google Chat" to "com.google.android.apps.dynamite",
        "Google-Chat" to "com.google.android.apps.dynamite",
        "GoogleClock" to "com.google.android.deskclock",
        "Google Clock" to "com.google.android.deskclock",
        "Google-Clock" to "com.google.android.deskclock",
        "GoogleContacts" to "com.google.android.contacts",
        "Google-Contacts" to "com.google.android.contacts",
        "Google Contacts" to "com.google.android.contacts",
        "google-contacts" to "com.google.android.contacts",
        "google contacts" to "com.google.android.contacts",
        "GoogleDocs" to "com.google.android.apps.docs.editors.docs",
        "Google Docs" to "com.google.android.apps.docs.editors.docs",
        "googledocs" to "com.google.android.apps.docs.editors.docs",
        "google docs" to "com.google.android.apps.docs.editors.docs",
        "Google Drive" to "com.google.android.apps.docs",
        "Google-Drive" to "com.google.android.apps.docs",
        "google drive" to "com.google.android.apps.docs",
        "google-drive" to "com.google.android.apps.docs",
        "GoogleDrive" to "com.google.android.apps.docs",
        "Googledrive" to "com.google.android.apps.docs",
        "googledrive" to "com.google.android.apps.docs",
        "GoogleFit" to "com.google.android.apps.fitness",
        "googlefit" to "com.google.android.apps.fitness",
        "GoogleKeep" to "com.google.android.keep",
        "googlekeep" to "com.google.android.keep",
        "GoogleMaps" to "com.google.android.apps.maps",
        "Google Maps" to "com.google.android.apps.maps",
        "googlemaps" to "com.google.android.apps.maps",
        "google maps" to "com.google.android.apps.maps",
        "Google Play Books" to "com.google.android.apps.books",
        "Google-Play-Books" to "com.google.android.apps.books",
        "google play books" to "com.google.android.apps.books",
        "google-play-books" to "com.google.android.apps.books",
        "GooglePlayBooks" to "com.google.android.apps.books",
        "googleplaybooks" to "com.google.android.apps.books",
        "GooglePlayStore" to "com.android.vending",
        "Google Play Store" to "com.android.vending",
        "Google-Play-Store" to "com.android.vending",
        "GoogleSlides" to "com.google.android.apps.docs.editors.slides",
        "Google Slides" to "com.google.android.apps.docs.editors.slides",
        "Google-Slides" to "com.google.android.apps.docs.editors.slides",
        "GoogleTasks" to "com.google.android.apps.tasks",
        "Google Tasks" to "com.google.android.apps.tasks",
        "Google-Tasks" to "com.google.android.apps.tasks",
        "Joplin" to "net.cozic.joplin",
        "joplin" to "net.cozic.joplin",
        "McDonald" to "com.mcdonalds.app",
        "mcdonald" to "com.mcdonalds.app",
        "Osmand" to "net.osmand",
        "osmand" to "net.osmand",
        "PiMusicPlayer" to "com.Project100Pi.themusicplayer",
        "pimusicplayer" to "com.Project100Pi.themusicplayer",
        "Quora" to "com.quora.android",
        "quora" to "com.quora.android",
        "Reddit" to "com.reddit.frontpage",
        "reddit" to "com.reddit.frontpage",
        "RetroMusic" to "code.name.monkey.retromusic",
        "retromusic" to "code.name.monkey.retromusic",
        "SimpleCalendarPro" to "com.scientificcalculatorplus.simplecalculator.basiccalculator.mathcalc",
        "SimpleSMSMessenger" to "com.simplemobiletools.smsmessenger",
        "Telegram" to "org.telegram.messenger",
        "temu" to "com.einnovation.temu",
        "Temu" to "com.einnovation.temu",
        "Tiktok" to "com.zhiliaoapp.musically",
        "tiktok" to "com.zhiliaoapp.musically",
        "Twitter" to "com.twitter.android",
        "twitter" to "com.twitter.android",
        "X" to "com.twitter.android",
        "VLC" to "org.videolan.vlc",
        "WeChat" to "com.tencent.mm",
        "wechat" to "com.tencent.mm",
        "Whatsapp" to "com.whatsapp",
        "WhatsApp" to "com.whatsapp",
    )

    private val NORMALIZED: Map<String, String> by lazy {
        APP_PACKAGES.entries.associate { (k, v) -> k.lowercase().trim() to v }
    }

    /**
     * System apps differ wildly by OEM. For each canonical app we keep a
     * priority-ordered list of possible packages; the launcher walks the
     * list until one succeeds.
     */
    private val SYSTEM_ALIASES: Map<String, List<String>> = mapOf(
        "设置" to listOf(
            "com.android.settings",                // AOSP/EMUI/MagicOS 都走这个
            "com.hihonor.settings", "com.huawei.settings",
            "com.miui.settings", "com.oppo.settings", "com.vivo.settings",
        ),
        "settings" to listOf("com.android.settings", "com.hihonor.settings", "com.huawei.settings"),
        "系统设置" to listOf("com.android.settings", "com.hihonor.settings", "com.huawei.settings"),
        "日历" to listOf(
            "com.hihonor.calendar",          // Honor MagicOS 7+ (荣耀独立后)
            "com.huawei.calendar",           // HMS / EMUI 老版本
            "com.android.calendar",          // AOSP
            "com.miui.calendar", "com.android.calendar3",
            "com.google.android.calendar",
        ),
        "calendar" to listOf(
            "com.hihonor.calendar", "com.huawei.calendar", "com.android.calendar",
            "com.google.android.calendar",
        ),
        "时钟" to listOf("com.android.deskclock", "com.huawei.deskclock", "com.android.alarmclock"),
        "闹钟" to listOf("com.android.deskclock", "com.huawei.deskclock"),
        "clock" to listOf("com.android.deskclock", "com.huawei.deskclock"),
        "计算器" to listOf("com.android.calculator2", "com.huawei.calculator", "com.miui.calculator"),
        "calculator" to listOf("com.android.calculator2", "com.huawei.calculator", "com.miui.calculator"),
        "相机" to listOf("com.hihonor.camera", "com.huawei.camera", "com.android.camera", "com.android.camera2", "com.miui.camera"),
        "camera" to listOf("com.hihonor.camera", "com.huawei.camera", "com.android.camera", "com.android.camera2"),
        "相册" to listOf(
            "com.hihonor.photos", "com.huawei.photos",
            "com.android.gallery3d", "com.miui.gallery",
            "com.google.android.apps.photos",
        ),
        "图库" to listOf("com.hihonor.photos", "com.huawei.photos", "com.android.gallery3d", "com.miui.gallery"),
        "gallery" to listOf("com.hihonor.photos", "com.huawei.photos", "com.android.gallery3d", "com.miui.gallery"),
        "电话" to listOf("com.android.dialer", "com.huawei.contacts", "com.android.phone"),
        "拨号" to listOf("com.android.dialer", "com.huawei.contacts"),
        "phone" to listOf("com.android.dialer", "com.huawei.contacts"),
        "联系人" to listOf("com.android.contacts", "com.huawei.contacts", "com.android.dialer"),
        "通讯录" to listOf("com.android.contacts", "com.huawei.contacts"),
        "contacts" to listOf("com.android.contacts", "com.huawei.contacts"),
        "短信" to listOf("com.android.mms", "com.huawei.message", "com.android.messaging"),
        "信息" to listOf("com.huawei.message", "com.android.mms", "com.android.messaging"),
        "messages" to listOf("com.android.mms", "com.huawei.message"),
        "sms" to listOf("com.android.mms", "com.huawei.message"),
        "文件管理" to listOf("com.huawei.filemanager", "com.android.documentsui", "com.miui.filemanager"),
        "文件" to listOf("com.huawei.filemanager", "com.android.documentsui"),
        "files" to listOf("com.huawei.filemanager", "com.android.documentsui", "com.google.android.documentsui"),
        "录音机" to listOf("com.huawei.soundrecorder", "com.android.soundrecorder"),
        "录音" to listOf("com.huawei.soundrecorder", "com.android.soundrecorder"),
        "音乐" to listOf("com.android.mediacenter", "com.huawei.music", "com.tencent.qqmusic", "com.netease.cloudmusic"),
        "记事本" to listOf("com.example.android.notepad", "com.huawei.notepad"),
        "备忘录" to listOf("com.huawei.notepad", "com.example.android.notepad"),
        "天气" to listOf("com.huawei.android.totemweather", "com.miui.weather2"),
        "weather" to listOf("com.huawei.android.totemweather", "com.miui.weather2"),
        "浏览器" to listOf("com.huawei.browser", "com.android.browser", "com.android.chrome"),
        "browser" to listOf("com.huawei.browser", "com.android.browser", "com.android.chrome"),
        "应用市场" to listOf("com.huawei.appmarket", "com.huawei.appgallery", "com.android.vending"),
        "app store" to listOf("com.huawei.appmarket", "com.android.vending"),
        "智慧助手" to listOf("com.huawei.intelligent"),
        "桌面" to listOf("com.huawei.android.launcher", "com.android.launcher", "com.android.launcher3"),
        "launcher" to listOf("com.huawei.android.launcher", "com.android.launcher3"),
    )

    /** Single best package — kept for callers that don't accept a list. */
    fun getPackageName(appName: String): String? = candidates(appName).firstOrNull()

    /**
     * Return all candidate packages for the given user-facing name, in
     * priority order. The launcher tries them top-to-bottom.
     */
    fun candidates(appName: String): List<String> {
        val direct = APP_PACKAGES[appName] ?: NORMALIZED[appName.lowercase().trim()]
        val systemList = SYSTEM_ALIASES[appName]
            ?: SYSTEM_ALIASES[appName.lowercase().trim()]
            ?: emptyList()
        // If the model already passed a fully-qualified package (contains a dot
        // and lowercase letters), keep it at the front of the list.
        val looksLikePackage = appName.contains('.') && appName.all { it == '.' || it.isLetterOrDigit() || it == '_' }
        val seed = if (looksLikePackage) listOf(appName) else emptyList()
        return (seed + listOfNotNull(direct) + systemList).distinct()
    }

    fun getAppName(packageName: String): String? =
        APP_PACKAGES.entries.firstOrNull { it.value == packageName }?.key

    fun listSupportedApps(): List<String> = APP_PACKAGES.keys.toList()
}
